rootProject.name = "SimpleHIIT"
include(":app")
include(":data")
include(":dataInstrumentedTests")
include(":commonDomain")
include(":commonUtils")
include(":commonResources")
include(":testUtils")
include(":android:mobile:ui:common")
include(":android:mobile:ui:home")
