rootProject.name = "SimpleHIIT"
include(":app")
include(":commonUtils")
include(":testUtils")
include(":domain:common")
include(":domain:home")
include(":domain:settings")
include(":domain:statistics")
include(":domain:session")
include(":data")
include(":dataInstrumentedTests")
include(":commonResources")
include(":android:mobile:ui:common")
include(":android:mobile:ui:home")
include(":android:mobile:ui:session")
include(":android:mobile:ui:settings")
include(":android:mobile:ui:statistics")
