object Versions {

    const val gradlePlugin = "7.4.0"
    const val kotlin = "1.3.61"
    const val appCompat = "1.6.1"
    const val datastore = "1.0.0"
    const val material = "1.9.0"
    const val jupiter = "5.9.3"
    const val junit = "1.1.5"
    const val androidXcoreKtx = "1.10.1"
    const val hilt = "2.48"
    const val hiltNavigation = "1.0.0"
    const val room_version = "2.6.0-rc01" // latest stable version is 2.5.2, but is incompatible with kotlin 1.9+, breaking build on suspend methods. V.2.5.3 is expected to fix this but not out yet. see https://issuetracker.google.com/issues/236612358
    const val composeMaterial3WindowSizeClass = "1.1.1"
    const val nav_version = "2.6.0"
    const val mockkVersion = "1.13.8"
    const val coroutinesTest = "1.7.3"
    const val core_testing = "2.2.0"
    const val test_runner = "1.5.2"
    const val coil = "2.4.0"
    const val benManesDependenciesVersionPlugin = "0.48.0"
    const val gmazzoJacocoReportAggregationPlugin = "1.1.1"
    const val savvasdalkitsisDependencyGraphPlugin = "0.12"
    const val composeBom = "2023.06.01"
    const val activityCompose = "1.7.0"
    const val composeTV = "1.0.0-alpha07"
}