object Versions {

    const val gradlePlugin = "7.4.0"
    const val kotlin = "1.3.61"
    const val appCompat = "1.6.1"
    const val datastore = "1.0.0"
    const val material = "1.3.0"
    const val jupiter = "5.9.3"
    const val junit = "1.1.5"
    const val androidXcoreKtx = "1.10.1"
    const val hilt = "2.46.1"
    const val hiltNavigation = "1.0.0"
    const val room_version = "2.5.1"
    const val nav_version = "2.5.3"
    const val mockkVersion = "1.13.5"
    const val coroutinesTest = "1.7.1"
    const val core_testing = "2.2.0"
    const val test_runner = "1.5.2"
    const val coil = "2.4.0"
    const val benManesDependenciesVersionPlugin = "0.46.0"
    const val gmazzoJacocoReportAggregationPlugin = "1.1.0"
    const val composeBom = "2023.05.01"
    const val activityCompose = "1.7.0"
}